#!/bin/sh

# debian bug 790422: accept empty input file

set -e

this=dose-debcheck
indir=debian/tests/repos
outdir=${ADT_ARTIFACTS}/${this}
mkdir -p ${outdir}

packfile=/dev/null
base=$(basename $packfile)

dose-debcheck ${packfile} 2> /dev/null \
    | tee ${outdir}/${base}.out \
    | grep -q "broken-packages: 0"
