#!/bin/sh

# debian bug 867104: wanna-build issue with src:perl versioned Provides

set -e

this=dose-debcheck
indir=debian/tests/repos
outdir=${ADT_ARTIFACTS}/${this}
mkdir -p ${outdir}

packfile=$indir/virtual_and_real
base=$(basename $packfile)

dose-debcheck --checkonly=main ${packfile} \
    | tee ${outdir}/${base}.out \
    | grep -q "broken-packages: 0"
