#!/bin/sh

# debian bug 811569: accept weird characters in debian field names

set -e

this=dose-debcheck
indir=debian/tests/repos
outdir=${ADT_ARTIFACTS}/${this}
mkdir -p ${outdir}

packfile=$indir/weird.fields.Packages
base=$(basename $packfile)

dose-debcheck ${packfile} \
    | tee ${outdir}/${base}.out \
    | grep -q "broken-packages: 0"
