#!/bin/sh

set -e

this=dose-builddebcheck
indir=debian/tests/repos
outdir=${ADT_ARTIFACTS}/${this}
mkdir -p ${outdir}

packfile=$indir/Packages1
srcfile=$indir/Sources1

base=$(basename $packfile)
dose-builddebcheck --deb-native-arch=toaster ${packfile} ${srcfile} \
    | tee ${outdir}/${base}.out \
    | grep -q "broken-packages: 0"
